### ISSUE TITLE
Insecure SSL security policy

### ISSUE THREAD

**Issue by nicklester** [cfn-modules/alb-listener#10]
It appears the default Alb Listener configuration still permits TLS 1.0 - and the module doesn't seem to allow for this to be overridden in AWS::ElasticLoadBalancingV2::Listener . I think we need to be using a higher level of SSL Policy given that PCI DSS v3.2 required that TLS 1.0 be disabled entirely as of June 30, 2018.

**Comment by michaelwittig** [comment]
Setting the `SslPolicy` property to `ELBSecurityPolicy-TLS-1-2-Ext-2018-06` should do the trick, right?

**Comment by nicklester** [comment]
Hi - yes that's my understanding

**Comment by michaelwittig** [comment]
I had a conversation with someone how understands more of this topic and he suggested to go with `ELBSecurityPolicy-FS-1-2-Res-2019-08` which I now do in #11

**Comment by michaelwittig** [comment]
released as v1.2.0
